# Generated by Django 4.1.1 on 2022-09-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=15, verbose_name="Государственный номер"
                    ),
                ),
                ("marka", models.CharField(max_length=50, verbose_name="Марка")),
                ("model", models.CharField(max_length=50, verbose_name="Модель")),
                ("vin", models.CharField(max_length=17, verbose_name="ВИН номер")),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastname", models.CharField(max_length=15, verbose_name="Фамилия")),
                ("firstname", models.CharField(max_length=15, verbose_name="Имя")),
                (
                    "middlename",
                    models.CharField(max_length=15, verbose_name="Отчество"),
                ),
                (
                    "phone",
                    models.CharField(max_length=11, verbose_name="Номер телефона"),
                ),
                ("adress", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["lastname"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod",
                    models.CharField(max_length=10, verbose_name="Каталожный номер"),
                ),
                (
                    "nameproduct",
                    models.CharField(max_length=20, verbose_name="Название товара"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["cod"],
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod",
                    models.CharField(max_length=10, verbose_name="Каталожный номер"),
                ),
                (
                    "nameproduct",
                    models.CharField(max_length=20, verbose_name="Название работы"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
                "ordering": ["cod"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datepub", models.DateTimeField(auto_now=True)),
                (
                    "auto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seau.auto",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seau.client",
                        verbose_name="клиент",
                    ),
                ),
                ("product", models.ManyToManyField(to="seau.product")),
                ("work", models.ManyToManyField(to="seau.work")),
            ],
            options={
                "verbose_name": "Заказ-наряд",
                "verbose_name_plural": "Заказ-наряды",
            },
        ),
    ]
