# Generated by Django 4.1.1 on 2022-09-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seau", "0002_alter_order_auto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="auto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="seau.auto",
                verbose_name="Автомобиль",
            ),
        ),
    ]
