# Generated by Django 4.1.1 on 2022-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seau", "0004_alter_order_datepub_alter_order_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="work",
            field=models.ManyToManyField(to="seau.work"),
        ),
    ]
